#!/bin/sh
# Invert hex color

[ -t 0 ] || set -- $(cat) $*
for i; do
	hex=${i#\#}
    set -- $(hex2rgb "$hex")

    r=$(($1*-1+255))
    g=$(($2*-1+255))
    b=$(($3*-1+255))
	printf '%02x%02x%02x\n' "$r" "$g" "$b"
done
